server {
    host        127.0.0.1
    port        8080

    # error_page  404 /errors/404.html 
    error_page  500 /errors/500.html

    client_max_body_size 10000000

    location / {
        methods     GET
        root        /var/www/html
        index       index.html
        autoindex   off
    }

    location /uploads {
        methods         GET POST DELETE
        root            /var/www
        upload_store    /var/www/uploads
        autoindex       on
        client_max_body_size 5000000
    }

    location /old {
        methods     GET
        redirect    /new
    }

    location /new {
        methods     GET
        root        /var/www/html
        index       new.html
    }

    location /cgi-bin {
        methods     GET POST
        root        /var/www/cgi-bin
        cgi_ext     .py
    }
}

server {
    host        127.0.0.1
    port        8081

    error_page  404 /errors/404.html

    client_max_body_size 1000000

    location / {
        methods     GET
        root        /var/www/site2
        index       index.html
        autoindex   off
    }

    location /api {
        methods     GET POST
        root        /var/www/site2/api
        cgi_ext     .php
    }
}

server {
    host        127.0.0.1
    port        9000

    error_page  404 /errors/404.html
    error_page  403 /errors/403.html

    client_max_body_size 50000000

    location / {
        methods     GET
        root        /var/www/site3
        autoindex   on
    }
}